#!/usr/bin/env bash
#
# hosts - a safe command-line manager for /etc/hosts
#
# This file is generated by "make build" from src/*.sh.
# Do not edit it directly; edit the sources and rebuild.
#
# Homepage: https://github.com/n36l3c7/hosts-cli
# Licence:  MIT

set -euo pipefail

if [[ -z ${BASH_VERSINFO[0]:-} ]] ||
  ((BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 4))); then
  printf 'hosts: bash 4.4 or newer is required (running %s)\n' \
    "${BASH_VERSION:-unknown}" >&2
  exit 1
fi
